
services:
  mongo:
   image: mongo:latest
   container_name: codexhub-mongo
   ports:
     - "27017:27017"
   volumes:
     - mongo_data:/data/db
   networks:
     - codexhub_net

  backend:
   build: ./backend
   container_name: codexhub-backend
   ports:
     - "5001:5001"
   depends_on:
     - mongo
   environment:
     - MONGO_URI=mongodb://mongo:27017/bookstore
   networks:
     - codexhub_net

  frontend:
   build: ./frontend
   container_name: codexhub-frontend
   ports:
     - "5173:5173"
   depends_on:
     - backend
   networks:
     - codexhub_net

networks:
    codexhub_net:
      driver: bridge

volumes:
  mongo_data: