kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: codexhub-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
  volumeName: codexhub-pv