@Library('Shared') _
pipeline {
    agent any
    
    parameters {
       string(name: 'DOCKER_TAG', defaultValue: '', description: 'Tag for Docker Images From CI ')
    }

    stages {
        stage("Workspace cleanup"){
            steps{
                script{
                    cleanWs()
                }
            }
        }
        
        stage('Git: Code Checkout') {
            steps {
                script{
                    code_checkout("https://github.com/rohitDev450/CodexHub-Mega-Project.git","main")
                }
            }
        }
        
        stage('Verify: Docker Image Tags') {
            steps {
                script{
                    echo "DOCKER_TAG: ${params.DOCKER_TAG}"
                }
            }
        }
        
        stage("Update: Kubernetes manifests") {
            steps {
                script {
                    dir('k8s') {
                        sh """
                            sed -i -E "s#image:.*rohitar/codexhub-mega-project-backend:.*#image: rohitar/codexhub-mega-project-backend:${params.DOCKER_TAG}#g" backend-deployment.yml
                        """
                    }
                
                    dir('kubernetes') {
                        sh """
                            sed -i -E "s#image:.*rohitar/codexhub-mega-project-frontend:.*#image: rohitar/codexhub-mega-project-frontend:${params.DOCKER_TAG}#g" frontend-deployment.yml
                        """
                    }
                }
            }
        }

        stage("Git: Code update and push to GitHub"){
            steps {
                script {
                    withCredentials([gitUsernamePassword(credentialsId: 'Github-cred', gitToolName: 'Default')]) {
                        sh '''
                        echo "Checking repository status: "
                        git status
                    
                        echo "Adding changes to git: "
                        git add .
                        
                        echo "Committing changes (if any): "
                        git commit -m "Updated image tags" || echo "No changes to commit"
                        
                        echo "Pushing changes to GitHub: "
                        git push origin main
                        '''
                    }
                }
            }
        }
    }
}
